### ISSUE TITLE
currency formatting doesn't work when locale is 'C'

### ISSUE THREAD

**Issue by fcqueiroz** [fcqueiroz/finerplan#29]
**Describe the bug**
Locale didn't allow the application to start because of an error

```
Traceback (most recent call last):  
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app  
    response = self.full_dispatch_request()  
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request  
    rv = self.handle_user_exception(e)  
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception  
    reraise(exc_type, exc_value, tb)  
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise  
    raise value  
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request  
    rv = self.dispatch_request()  
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request  
    return self.view_functions[rule.endpoint](**req.view_args)  
  File "./finerplan/frontend/__init__.py", line 30, in overview  
    basic_report = reports.basic()  
  File "./finerplan/core/reports.py", line 80, in basic  
    return {'earnings': locale.currency(earnings, grouping=True),  
  File "/usr/lib/python3.8/locale.py", line 267, in currency  
    raise ValueError("Currency formatting is not possible using "  
ValueError: Currency formatting is not possible using the 'C' locale.
```

**To Reproduce**
Change environment locale to [POSIX default](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap07.html#tag_07_02) and run the development web server.
```
/home/user/finerplan_folder$ unset LANG  
/home/user/finerplan_folder$ flask run  
```
GET request from localhost:5001/ should return 500 INTERNAL SERVER ERROR

**Expected behavior**
The application should handle POSIX/C locale by setting a default option that is capable of currency formatting

**Comment by fcqueiroz** [comment]
https://github.com/fcqueiroz/finerplan/pull/2 attempts to solve this, but still fails inside a docker environment.

In some situations the chosen locale won't be available and the application will fail is spite of the efforts.

Here is another (failed) attempt to set the locale:
```
def _assure_locale(default="pt_BR.UTF-8", verified=('LC_MONETARY', 'LC_TIME')):
    """Prevent Bug #29 by setting the default locale as pt_BR.UTF-8.

    :param default:
        The default locale in case it is not defined for the system.
    :param verified:
        A tuple containing the locale settings that must be configured.
    """
    locale.setlocale(locale.LC_ALL, '')

    for lc in verified:
        language_code, encoding = locale.getlocale(category=getattr(locale, lc))
        if language_code is None or encoding is None:
            locale.setlocale(locale.LC_ALL, default)
            break
```

All these attempts fail because, despite recognizing an unset locale, they have no control over system available locales. Therefore, the right locale configuration is a current application dependency that must be provided by the host system.

The revised proposed solution is to document this dependency and fail application start whenever a POSIX/C locale is detected.
